name: Dougmysticeye
favicon: null
layout_spectrum: 0.3591171333100647
typography_spectrum: 0.38638257677666843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
